services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - ./:/var/www
    environment:
      LARAVEL_BYPASS_ENV_CHECK: "1"
